//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public int StatID { get; set; }
        public int StudentID { get; set; }
        public int TestID { get; set; }
        public byte Result { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Test Test { get; set; }
    }
}
